LPS-146764 Export depot connecitons between staging and live
liferay-lima/liferay-portal pull request #2711
Opened 2022-02-04 13:23 UTC by adolfopa

2022-02-04 13:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-02-04 13:23 UTC, adolfopa commented
ci:test:sf

2022-02-04 13:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>depot</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/432/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/432/jenkins-report.html">here</a>.</b></p>

2022-02-04 13:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/280/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/280/jenkins-report.html">here</a>.</b></p>

2022-02-04 13:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2f48da96be1919b5656864a4619c22ed554eeee">d2f48da96be1919b5656864a4619c22ed554eeee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/adolfopa/liferay-portal/tree/LPS-146764">LPS-146764</a><br/>Branch GIT ID: <a href="https://github.com/adolfopa/liferay-portal/commit/fa0c21ce946f6ea0e993cd5da438f91b1c41d464">fa0c21ce946f6ea0e993cd5da438f91b1c41d464</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/280/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/280/jenkins-report.html">here</a>.</h5></details></html>

2022-02-04 13:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/280/">test-portal-source-format#280</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/280/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/2711">liferay-lima#2711</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1607518813">[master] ci:test:sf - adolfopa &gt; liferay-lima - PR#2711 - 2022-02-04[05:24:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/1052/">publish-testray-report#1052</a><br/></div></div>

2022-02-04 15:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:depot - 3 out of 10 jobs passed in 2 hours 26 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2888">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1367401_432</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2f48da96be1919b5656864a4619c22ed554eeee">d2f48da96be1919b5656864a4619c22ed554eeee</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a7d43f7e8541dda4826f8cb06c4f3b336c294529">a7d43f7e8541dda4826f8cb06c4f3b336c294529</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2887">Acceptance Upstream DXP (master) #2887</a></p><details><summary><strong>ci:test:depot - 3 out of 10 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/432/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/17696/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2049/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9791/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20519/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/487886/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28416/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>3 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/487885/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28415/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28673/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/432/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/17696/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>47 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21/17696//consoleText">AXIS_VARIABLE=21 #17696</a><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21/17696//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DepotRemoteStagingDM_CanNotViewImageFromDisconnectedSite_">LocalFile.DepotRemoteStagingDM#CanNotViewImageFromDisconnectedSite</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.DepotRemoteStagingDM_CanNotViewImageFromDisconnectedSite/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.DepotRemoteStagingDM_CanNotViewImageFromDisconnectedSite/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/21/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=23/17696//consoleText">AXIS_VARIABLE=23 #17696</a><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=23/17696//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DepotRemoteStagingDM_CanPublishAssetFromSiteWidget_">LocalFile.DepotRemoteStagingDM#CanPublishAssetFromSiteWidget</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/23/LocalFile.DepotRemoteStagingDM_CanPublishAssetFromSiteWidget/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/23/LocalFile.DepotRemoteStagingDM_CanPublishAssetFromSiteWidget/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/23/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=24/17696//consoleText">AXIS_VARIABLE=24 #17696</a><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=24/17696//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DepotRemoteStagingDM_CanPublishDMWithDocumentType_">LocalFile.DepotRemoteStagingDM#CanPublishDMWithDocumentType</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/24/LocalFile.DepotRemoteStagingDM_CanPublishDMWithDocumentType/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/24/LocalFile.DepotRemoteStagingDM_CanPublishDMWithDocumentType/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-02/test-1-36/test-portal-acceptance-pullrequest(master)/432/functional-tomcat90-mysql57-jdk8/0/24/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2049/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results: [...]

2022-02-04 16:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/432/">test-portal-acceptance-pullrequest(master)#432</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/432/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>depot<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/2711">liferay-lima#2711</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1607624158">[master] ci:test:depot - adolfopa &gt; liferay-lima - PR#2711 - 2022-02-04[05:23:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/1060/">publish-testray-report#1060</a><br/></div></div>

2022-02-07 07:57 UTC, Hanlf commented
Hi @adolfopa 
There are 1 test fix and 3 portal issues after analyzing the depot tests result, let me know if you need more info or any other help.

- For the Poshi case issue, could you please fetch the last commit(8247a44) of my [PR](https://github.com/Hanlf/liferay-portal/pull/310) first when you fix the portal issue? I prefer to use your original PR rather than opening a new PR by me, thanks!

- For the portal issues, please see the below for details:

**Issue 1: Asset library cannot be selected on connected site when staging is enabled**
Steps:
1. Add a new site
2. Add a depot and connect to the added site
3. Enable local staging for the site and depot
4. Upload an image to Documents and Media in the depot 
5. Go to the staging site > Blogs
6. Add a blog entry and try to select the image from the depot
**Result:** The depot not showing in the item selector

**Issue 2: Show the depot name in the Connected sites table after enabling local staging**
Steps:
1. Add a new site
2. Add a depot and connect to the added site
3. Go to Asset Library Settings > Sites to assert the Name is site name in the Connected sites
4. Enable local staging for the depot
5. Go to Asset Library Settings > Sites to assert the Name column
**Result:** The name is updated to depot name, instead of the site name

**Issue 3: Fail to publish documents to live on the site when using DM type from depot**
Steps:
1. Enable remote staging for depot and site
2. Go to Asset Library Settings > Sites to Make Structures Available
3. Add a new DM type in the depot
4. Publish it to live in the depot
5. Go to the staging site > DM to add a new document using the new DM type from the depot
6. Try to publish it to live
**Result:** Fail to publish documents to live on the site for remote staging
**Note:** not sure if local staging has the same issue, which is blocked by another issue: no depot document type shows on the connected site, I guess should be the same root cause of Issue 2.
Error throws on the console:
```
2022-02-07 06:59:39.947 ERROR [liferay/background_task-9][LoggerExportImportLifecycleListener:196] Layout remote publication failed for group 43649
2022-02-07 06:59:40.072 ERROR [liferay/background_task-9][BackgroundTaskMessageListener:182] Unable to execute background task
com.liferay.portal.kernel.exception.PortalException: Invocation failed due to com.liferay.exportimport.kernel.lar.PortletDataException
	at com.liferay.portal.servlet.TunnelServlet.doPost(TunnelServlet.java:117) ~[portal-impl.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[servlet-api.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at com.liferay.shielded.container.internal.proxy.ServletWrapper.service(ServletWrapper.java:113) ~[com.liferay.shielded.container.impl.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147) ~[portal-kernel.jar:?]
	at com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilter.processFilter(AuthVerifierFilter.java:212) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) ~[portal-kernel.jar:?]
	at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) ~[portal-kernel.jar:?]
	at com.liferay.portal.servlet.filters.lockout.LockoutFilter.processFilter(LockoutFilter.java:58) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147) ~[portal-kernel.jar:?]
	at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147) ~[portal-kernel.jar:?]
	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:245) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99) ~[portal-kernel.jar:?]
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) ~[urlrewritefilter.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[urlrewritefilter.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) ~[urlrewritefilter.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) ~[urlrewritefilter.jar:4.0.4]
	at com.liferay.portal.url.rewrite.filter.internal.URLRewriteFilter.processFilter(URLRewriteFilter.java:98) ~[?:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.process [...]

2022-02-07 14:15 UTC, AliciaGarciaGarcia requested changes

2022-02-07 14:47 UTC, adolfopa commented on modules/apps/depot/depot-service/src/main/java/com/liferay/depot/service/impl/DepotEntryGroupRelLocalServiceImpl.java
> +		depotEntryGroupRel.setGroupId(_getDepotGroupId(depotEntryId));
Thanks Alicia. I'm going to skip the upgrade; we'll have to keep the groupId = depotGroupId association. There are more places that assume that, and I don't feel comfortable with changing so much stuff. So, we'll let sites "own" the connection and document that as a known behaviour.

2022-02-07 14:49 UTC, adolfopa commented
I've pushed the changes into https://github.com/liferay-lima/liferay-portal/pull/2712; let's see if everything is green there. Thanks @Hanlf and @AliciaGarciaGarcia !

2022-02-07 14:49 UTC, closed without merging