LPS-145476 Modify methos to obtain the URL with the new FrienlyURL
liferay-lima/liferay-portal pull request #2967
Opened 2022-04-25 10:23 UTC by AliciaGarciaGarcia

- LRQA-74499 No need to set password with token login
- LPS-113546 Modernize toggleeControls
- LPS-113546 Inline Liferay._editControlsState
- LPS-152006 Fix NullPointerException
- LPS-151981 Moves code since we also need to executed the updateLayout method and for this case we also need to execute updateLookAndFeel
- LPS-146970 Separate the message bus destination creation into a MessagingConfigurator class to avoid double-registration problems caused by exceptions thrown in the activate method
- LPS-146970 Move the initialization and registration of BackgroundTask related MessageListeners into their own classes
- LPS-146970 Publish only the MessageListener class as a service
- LPS-146970 Use the backgroundLocalService directly to be able to remove the backgroundTaskManager dependency from MessageListeners. With this, it's possible to wire destinations and listeners into the BackgroundTaskMessagingConfigurator
- LPS-146970 Wire destinations and listeners into configurator class instead
- LPS-146970 Inline
- LPS-146970 Not needed
- LPS-146970 Not needed as the DefaultMessageBus already triggers the destination destroy process
- LPS-146970 Use a list for better performance
- LPS-146970 Remove unused field.
- LPS-146970 Use MapUtil
- LPS-139102 Add bnd instruction to maven templates
- LPS-139102 Update project template tokens
- LPS-139102 Add expression to default list
- LPS-139102 SF duplicate code
- LPS-139102 SF
- LPS-139102 Fix typos
- LPS-149478 Update templates to use dart sass since other sass compilers are no longer supported
- LPS-149478 Remove unneeded tests
- LPS-139102 Cleanup RESTbuilder template
- LPS-149478 Use old css builder for theme builder projects
- LPS-139102 Cleanup RESTBuilder template versions
- LPS-139102 Update Tests to use latest
- LPS-139102 Specify vulcan api version for 7.3 and 7.4
- LPS-139102 SF
- LPS-139102 Temporarily ignore test failures
- LPS-139102 match existing usage
- LPS-139102 prep next
- COMMERCE-9097 batch-engine-service - delete child entries
- COMMERCE-9097 batch-planner-web - rename to templateName, we already have input with "name" id
- COMMERCE-9097 batch-planner-web - apply changes
- LPS-151649 New test added: User Can navigate to a Home Page after Site is created
- LPS-151649 Ignore test LiferayboticsHomePage until Site is visible.
- LPS-151649. New test added. User can navigate to a Dashboard Page
- LPS-151649 Ignore test LiferayboticsDashboardPage until Site is visible.
- LPS-77699 Update Translations
- COMMERCE-9122 Add new locators for addresses dropdown
- COMMERCE-9122 Revamp test and fix issues
- LPS-152020 No need to limit file extensions
- LPS-152020 SF
- LPS-151526 make the cacheControl value be required
- LPS-151756 Add PUBLISH_STAGING permission to Asset Library so that a non-owner can publish to live
- LPS-151760 Add VIEW_STAGING resource action to Asset Library, so that the user can be assigned permissions to view Staged content in an Asset Library
- LPS-151064 The export translation needs if exist the draft id of the layout to know which data must be  the one of the draft on the default experience not the one of the published
- LPS-151905 Add new service method to get all DepotAppCustomizations by depotEntryId
- LPS-151905 Copy the DepotAppCustomizations to the staging DepotEntry when creating the new DepotEntry during the staging enabling process
- LPS-151905 Autogenerated
- LPS-151905 Semantic versioning
- LPS-152002 Check also for onClick null, we may have icon but not onClick
- COMMERCE-9072 fix missing index upgrade
- COMMERCE-9072 dummy step to update index
- COMMERCE-9072 update schema version
- LPS-151977 Typo
- LPS-146278 Remove the container of input field
- LPS-146278 Change site creation success message
- LPS-146278 Add language key
- LPS-146278 Remove not needed language key
- LPS-146278 Change toast alert styles
- LPS-146278 buildLang
- LPS-146278 Good enough
- LPS-146278 Regen
- LPS-146163 Delete FF.
- LPS-151626 add LOL properties
- LPS-151626 use nightly
- LPS-151001: Missing paddings between fragments after upgrading from 7.2 to 7.3
- LPS-151001 In order to better performance avoid continue if config values is empty
- LPS-151622 Adds new dummy step to force index update, removes the old IX_789CF949 and creates the new ones
- LPS-148353 Remove fragment advanced options feature flag
- LPS-148353 Remove feature flag from poshi testcases
- LPS-151602 Reduced z-index value from default for sticky-top management toolbar.
- LPS-151953 _objectEntryLocalService.addOrUpdateObjectEntry using ERC
- LPS-151953 validate ERC to avoid update wrong entity
- LPS-152031 Ensure FDS IDs are unique in DXP scope
- LPS-150774 Remove Feature Flag for LPS-146889
- LPS-150774 Fix Poshi tests
- LPS-150774 Add new module for object test utilities
- LPS-150774 Fix integration tests
- LPS-151324 Fix poshi test
- LPS-151324 Convert edit_object_relationship to React
- LPS-150036 Create Application Products Chart
- LPS-150036 Improving code
- LPS-150036 upload
- LPS-151393 Export image URL correctly when image is entered as a URL
- LPS-151393 Export image link correctly when image link is entered as a URL
- LPS-151393 Avoid exporting an empty JSON object for value_i18n in link
- LPS-151393 Process localized links during import
- LPS-151393 Add helper method in test class to create Fragment Entry with editable element of type image
- LPS-151393 Create import & export test for fragment with image element where image is mapped and link is mapped
- LPS-151393 Create import & export test for fragment with image element where image is mapped and link is set to a page
- LPS-151393 Create import & export test for fragment with image element where image is set to a URL and link is set to a URL
- LPS-151393 Adapt tests removing empty value_i18n JSON object from fragmentLink
- LPS-151393 SF
- LRQA-74332 Change macros to wait for sidebar be fully open
- LRQA-74332 Fix sidebar's paths
- LRQA-74332 Change path used in macro
- LRQA-74332 Refactor tests for better usage of sidebar's paths
- LRAC-10992 Quarantine test membership takes too long to update
- LPS-152014 Add logic for update comment by Wordsmith
- LPS-152014 Add test case
- LPS-152014 SF, rename
- LPS-151747 Create asset-vocabulary-item-selector-api module
- LPS-151747 Create AssetVocabularyItemSelectorCriterion and AssetVocabularyItemSelectorReturnType
- LPS-151747 Adds needed criteria
- LPS-151747 Baseline
- LPS-151747 Create asset-vocabulary-item-selector-web module
- LPS-151747 Adds a handle for AssetVocabularyItemSelectorCriterion.
- LPS-151747 Create AssetVocabularyItemSelectorView
- LPS-151747 Copy and adapt view from modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/view_vocabularies.jsp
- LPS-151747 Set row data to accomplish with the return type
- LPS-151747 Adds Site or Library table column
- LPS-151747 Handle MultiSelection
- LPS-151747 Pass itemSelectedEventName to the view
- LPS-151747 Pass return type class and multi-selection to the view
- LPS-151747 Handle single selection
- LPS-151747 Adds javadoc for easy use
- LPS-151747 Add required dependencies
- LPS-151747 Implements ItemSelectorViewDescriptor to avoid unnecessary classes and code
- LPS-151747 Uses new ItemSelectorViewDescriptor instead of a custom one
- LPS-151747 Removes no necessary files
- LPS-151912 Fix SF serviceReferenceUtilClassNames properties without ",\"
- LPS-148422 Removes feature flag
- LPS-148422 Resolve conflict
- LPS-148422 Rename label name
- LPS-148422 Adapt case for path change
- LPS-148422 Modify locater for collection cell nested element
- LPS-148422 Modify locater for collection item in case and path
- LPS-152027 Removes deprecated methods and classes (7.2.x and 7.3.x) from asset modules
- LPS-152027 Removes method
- LPS-152027 baseline
- LPS-152027 Auto
- LPS-131088 Implement basic CTDisplayRenderer for Role
- LRCI-2944 Avoid ArrayIndexOutOfBoundsException
- LRCI-2944 prep next
- LPS-152071 Create test stubs
- LPS-128600 Extend [...]

2022-04-25 10:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-25 10:28 UTC, AliciaGarciaGarcia commented
ci:test:relevant

2022-04-25 10:28 UTC, AliciaGarciaGarcia commented
ci:test:sf

2022-04-25 10:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/2661/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2661/jenkins-report.html">here</a>.</b></p>

2022-04-25 10:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1100/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1100/jenkins-report.html">here</a>.</b></p>

2022-04-25 10:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f71017f9b43407a157834ee31edc16bd2b587b62">f71017f9b43407a157834ee31edc16bd2b587b62</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AliciaGarciaGarcia/liferay-portal/tree/LPS-145476">LPS-145476</a><br/>Branch GIT ID: <a href="https://github.com/AliciaGarciaGarcia/liferay-portal/commit/10f0e33dc2cbef9c14a246c1dd6a96b74f708d49">10f0e33dc2cbef9c14a246c1dd6a96b74f708d49</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1100/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1100/jenkins-report.html">here</a>.</h5></details></html>

2022-04-25 10:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1100/">test-portal-source-format#1100</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1100/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/2967">liferay-lima#2967</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1702209093">[master] ci:test:sf - AliciaGarciaGarcia &gt; liferay-lima - PR#2967 - 2022-04-25[03:29:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/4440/">publish-testray-report#4440</a><br/></div></div>

2022-04-25 12:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 29 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 28 out of 30 jobs passed in 1 hour 39 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f71017f9b43407a157834ee31edc16bd2b587b62">f71017f9b43407a157834ee31edc16bd2b587b62</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f71017f9b43407a157834ee31edc16bd2b587b62">f71017f9b43407a157834ee31edc16bd2b587b62</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3184">Acceptance Upstream DXP (master) #3184</a></p><details><summary><strong>ci:test:stable - 27 out of 29 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30273/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47756/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46428/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47752/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46432/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/43784/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47754/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46950/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/43785/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/490003/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1541/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46431/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22209/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/51138/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/33280/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22210/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47757/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1539/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1540/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1538/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46430/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46951/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22211/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/43782/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22208/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46429/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47755/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47753/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/43783/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 27 out of 30 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/2661/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30273/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47756/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/46428/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47752/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4 [...]

2022-04-25 12:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/2661/">test-portal-acceptance-pullrequest(master)#2661</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2661/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/2967">liferay-lima#2967</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1702259412">[master] ci:test:relevant - AliciaGarciaGarcia &gt; liferay-lima - PR#2967 - 2022-04-25[03:29:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/7370/">publish-testray-report#7370</a><br/></div></div>

2022-04-25 19:56 UTC, ambrinchaudhary approved these changes

2022-04-26 07:29 UTC, adolfopa requested changes

2022-04-26 07:29 UTC, adolfopa commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/helper/DLURLHelperImpl.java
> +		String queryString) {
The parameter sorting looks a bit weird (lexicographic order). Why not follow the same "logical" ordering as in `_getPreviewUuidURL`?

2022-04-26 09:57 UTC, AliciaGarciaGarcia commented
ci:test:sf

2022-04-26 09:57 UTC, AliciaGarciaGarcia commented
ci:test:relevant

2022-04-26 09:58 UTC, AliciaGarciaGarcia commented
@adolfopa I made the suggested changes and rebased due to branch conflicts

2022-04-26 09:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/2675/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2675/jenkins-report.html">here</a>.</b></p>

2022-04-26 09:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/562/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/562/jenkins-report.html">here</a>.</b></p>

2022-04-26 10:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ddb0c18e73ac5e04258fe51ea82bb29a5eae2c06">ddb0c18e73ac5e04258fe51ea82bb29a5eae2c06</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AliciaGarciaGarcia/liferay-portal/tree/LPS-145476">LPS-145476</a><br/>Branch GIT ID: <a href="https://github.com/AliciaGarciaGarcia/liferay-portal/commit/911af7415ae9a260ad54a5f989305d6874d2f921">911af7415ae9a260ad54a5f989305d6874d2f921</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/562/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/562/jenkins-report.html">here</a>.</h5></details></html>

2022-04-26 10:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/562/">test-portal-source-format#562</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/562/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/2967">liferay-lima#2967</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1703996298">[master] ci:test:sf - AliciaGarciaGarcia &gt; liferay-lima - PR#2967 - 2022-04-26[02:58:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/2351/">publish-testray-report#2351</a><br/></div></div>

2022-04-26 11:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/2675/">test-portal-acceptance-pullrequest(master)#2675</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2675/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/2967">liferay-lima#2967</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1704061282">[master] ci:test:relevant - AliciaGarciaGarcia &gt; liferay-lima - PR#2967 - 2022-04-26[02:58:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/7407/">publish-testray-report#7407</a><br/></div></div>

2022-04-26 11:53 UTC, AliciaGarciaGarcia commented
ci:test:relevant

2022-04-26 12:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2909/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2909/jenkins-report.html">here</a>.</b></p>

2022-04-26 14:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2909/">test-portal-acceptance-pullrequest(master)#2909</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2909/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/2967">liferay-lima#2967</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1704141907">[master] ci:test:relevant - AliciaGarciaGarcia &gt; liferay-lima - PR#2967 - 2022-04-26[05:46:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/7830/">publish-testray-report#7830</a><br/></div></div>

2022-04-26 15:47 UTC, adolfopa commented
ci:forward

2022-04-26 15:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-04-26 15:47 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-04-26 15:48 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/350//consoleFull)

2022-04-26 15:48 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/116591
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/350//consoleFull)

2022-04-26 15:48 UTC, closed without merging