LPS-153629 Add assetCategoryIds to automatic draft saving request
liferay-lima/liferay-portal pull request #3055
Opened 2022-05-19 11:01 UTC by ambrinchaudhary

2022-05-19 11:01 UTC, liferay-lima commented
ci:test:sf

2022-05-19 11:01 UTC, liferay-lima commented
ci:test:relevant

2022-05-19 11:01 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-19 11:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1598/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1598/jenkins-report.html">here</a>.</b></p>

2022-05-19 11:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/2321/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2321/jenkins-report.html">here</a>.</b></p>

2022-05-19 11:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8888cc73639e41d1bf272802e05903d37c5cf96e">8888cc73639e41d1bf272802e05903d37c5cf96e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ambrinchaudhary/liferay-portal/tree/pr-3048">pr-3048</a><br/>Branch GIT ID: <a href="https://github.com/ambrinchaudhary/liferay-portal/commit/7ad71b6a2c908d89e1c044f8d372da0d7eb8c74b">7ad71b6a2c908d89e1c044f8d372da0d7eb8c74b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2321/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2321/jenkins-report.html">here</a>.</h5></details></html>

2022-05-19 11:04 UTC, ambrinchaudhary commented
ci:forward

2022-05-19 11:04 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-05-19 11:04 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2022-05-19 11:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3982/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3982/jenkins-report.html">here</a>.</b></p>

2022-05-19 11:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2321/">test-portal-source-format#2321</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2321/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3055">liferay-lima#3055</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1854636880">[master] ci:test:sf - ambrinchaudhary &gt; liferay-lima - PR#3055 - 2022-05-19[04:01:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/8471/">publish-testray-report#8471</a><br/></div></div>

2022-05-19 11:13 UTC, ambrinchaudhary commented
cc/ @evibudai

2022-05-19 11:32 UTC, boton requested changes

2022-05-19 11:32 UTC, boton commented on modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/js/blogs.js
> +	}
I think that we don't need a collection here, if we have inputs with the same name we have another issue.
This function can be updated as:

```js
	_getValuesByName(name) {
		return document.querySelector(`input[name=${this._config.namespace}${name}]`)?.value || '';
	}
```

2022-05-19 11:48 UTC, boton approved these changes

2022-05-19 11:57 UTC, evibudai commented
Hi @ambrinchaudhary,
I reviewed your changes and this line:
``input[name=${this._config.namespace + name}]``
must contain the *.
like this:
``input[name*=${this._config.namespace + name}]``

I understand it can seem like it is unnecessary, but the name that we search looks something like this:
`'_com_liferay_blogs_web_portlet_BlogsAdminPortlet_assetCategoryIds_40437'`
the last part (40437) being the unique id of the vocabulary.
I used the * to search 
`'_com_liferay_blogs_web_portlet_BlogsAdminPortlet_assetCategoryIds`
This returns the required nodes regardless the id.

This method returns a collection. If the user chooses multiple categories that is how it needs to be forwarded to backend.

2022-05-19 12:16 UTC, evibudai commented
Hi @ambrinchaudhary,
I tried your solution and later @boton 's solution as well and they did not work as intended.
I got the same error message "Could not save draft".

My solution would be (including the changes):
![image](https://user-images.githubusercontent.com/97447507/169291105-e7bb7621-c266-4e2b-aa05-ca14e1122bf7.png)

2022-05-19 12:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1598/">test-portal-acceptance-pullrequest(master)#1598</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1598/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3055">liferay-lima#3055</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1854686509">[master] ci:test:relevant - ambrinchaudhary &gt; liferay-lima - PR#3055 - 2022-05-19[04:01:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/3963/">publish-testray-report#3963</a><br/></div></div>

2022-05-19 12:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 95 out of 96 jobs passed in 1 hour 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8888cc73639e41d1bf272802e05903d37c5cf96e">8888cc73639e41d1bf272802e05903d37c5cf96e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8888cc73639e41d1bf272802e05903d37c5cf96e">8888cc73639e41d1bf272802e05903d37c5cf96e</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3291">Acceptance Upstream DXP (master) #3291</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22960/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20580/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22001/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/23543/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21561/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22957/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21999/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22000/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/16028/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22889/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/24422/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22779/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20392/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22886/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/23544/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19985/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22244/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17484/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20581/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20582/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/9927/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/9890/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22884/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/9926/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22245/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21563/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 94 out of 96 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3982/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/23546/"><strike>functional-tomcat90-mysql57-jdk8/1/15</strike></a></li></ul></li></ul></div><details><summary><strong>94 Successful Jobs:</strong></summary><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/10225/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/16030/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22959/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19986/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22960/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19787/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17483/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/16027/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21562/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20579/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/22958/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pu [...]

2022-05-19 12:38 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/117700
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3982//consoleFull)

2022-05-19 12:45 UTC, boton commented
> Hi @ambrinchaudhary, I tried your solution and later @boton 's solution as well and they did not work as intended. I got the same error message "Could not save draft".
> 
> My solution would be (including the changes): ![image](https://user-images.githubusercontent.com/97447507/169291105-e7bb7621-c266-4e2b-aa05-ca14e1122bf7.png)

You are totally right I miss some updates in this component

2022-05-19 12:51 UTC, boton commented
> Hi @ambrinchaudhary, I reviewed your changes and this line: `input[name=${this._config.namespace + name}]` must contain the *. like this: `input[name*=${this._config.namespace + name}]`
> 
> I understand it can seem like it is unnecessary, but the name that we search looks something like this: `'_com_liferay_blogs_web_portlet_BlogsAdminPortlet_assetCategoryIds_40437'` the last part (40437) being the unique id of the vocabulary. I used the * to search `'_com_liferay_blogs_web_portlet_BlogsAdminPortlet_assetCategoryIds` This returns the required nodes regardless the id.
> 
> This method returns a collection. If the user chooses multiple categories that is how it needs to be forwarded to backend.

Oh no, it's [merged right now](https://github.com/brianchandotcom/liferay-portal/pull/117700#issuecomment-1131636888) but maybe we can send a follow-up with `input[name*=${this._config.namespace + name}]` maybe using the [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) with `^` instead of `*` makes sense if the only change the last part of the name.

```
input[name^=${this._config.namespace}${name}]`
```

2022-05-19 12:51 UTC, evibudai commented
Hi @boton,
Thank you for your confirmation!

2022-05-19 12:53 UTC, evibudai commented on modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/js/blogs.js
> +			`input[name=${this._config.namespace + name}]`
It would be even better with "^":
`input[name^=${this._config.namespace}${name}]`

2022-05-19 12:56 UTC, evibudai commented
Yes @boton, :) I just wrote the same idea, you're right!

2022-05-20 07:32 UTC, ambrinchaudhary commented
My apologises @evibudai, you are right, the "^" is necessary. I looked at the Tag field and as the names were the same, I supposed it would work for also for categories. Sorry!! 
I'll send the fix right now.

2022-05-20 07:41 UTC, evibudai commented
No problem! Thank you @ambrinchaudhary !  :)

2022-05-20 07:59 UTC, ambrinchaudhary commented
See https://github.com/liferay-lima/liferay-portal/pull/3062

2022-05-20 07:59 UTC, closed without merging