LPS-157078 Clean up KB - Asset renderer and display contexts
liferay-lima/liferay-portal pull request #3209
Opened 2022-07-01 12:16 UTC by adolfopa

2022-07-01 12:16 UTC, liferay-lima commented
ci:test:sf

2022-07-01 12:16 UTC, liferay-lima commented
ci:test:relevant

2022-07-01 12:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-01 12:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3514/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3514/jenkins-report.html">here</a>.</b></p>

2022-07-01 12:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/2619/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2619/jenkins-report.html">here</a>.</b></p>

2022-07-01 12:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/31e4a20dc53eb12ac4fd6af76734d508bdd4d461">31e4a20dc53eb12ac4fd6af76734d508bdd4d461</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/adolfopa/liferay-portal/tree/LPS-157078">LPS-157078</a><br/>Branch GIT ID: <a href="https://github.com/adolfopa/liferay-portal/commit/589c79d7364f7389bdc106d55b18ab7909b0e2b6">589c79d7364f7389bdc106d55b18ab7909b0e2b6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2619/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2619/jenkins-report.html">here</a>.</h5></details></html>

2022-07-01 12:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2619/">test-portal-source-format#2619</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2619/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3209">liferay-lima#3209</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1894388837">[master] ci:test:sf - adolfopa &gt; liferay-lima - PR#3209 - 2022-07-01[05:16:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/9469/">publish-testray-report#9469</a><br/></div></div>

2022-07-01 13:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 48 out of 49 jobs passed in 1 hour 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/31e4a20dc53eb12ac4fd6af76734d508bdd4d461">31e4a20dc53eb12ac4fd6af76734d508bdd4d461</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1414f5ca04e3956aefef8467d891297695689291">1414f5ca04e3956aefef8467d891297695689291</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3487">Acceptance Upstream DXP (master) #3487</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37266/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/34149/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40973/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40125/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36881/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40972/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89132/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/30133/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31900/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39773/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37371/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37267/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36189/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38623/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91990/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/35629/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/42581/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89133/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93728/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86338/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38381/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38624/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91989/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/33635/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40264/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39754/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 47 out of 49 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3514/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40126/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>47 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/35628/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36882/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/34315/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37266/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36102/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39755/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41356/">functional-tomcat90-mysql57-jdk8/0/1</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31899/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40263/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36188/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38380/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat9 [...]

2022-07-01 14:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3514/">test-portal-acceptance-pullrequest(master)#3514</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3514/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3209">liferay-lima#3209</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1894455672">[master] ci:test:relevant - adolfopa &gt; liferay-lima - PR#3209 - 2022-07-01[05:16:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/9474/">publish-testray-report#9474</a><br/></div></div>

2022-07-05 13:08 UTC, AliciaGarciaGarcia requested changes

2022-07-05 13:08 UTC, AliciaGarciaGarcia commented on modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/display/context/KBAdminManagementToolbarDisplayContext.java
> +	private boolean _hasAddKBFolderPermission() throws PortalException {
We are adding 2 times the folder on the creation menu

![image](https://user-images.githubusercontent.com/47524751/177334938-3eb7cc92-ab27-428e-a33b-cf6cb5f3c5ca.png)

2022-07-05 13:16 UTC, AliciaGarciaGarcia requested changes

2022-07-05 13:16 UTC, AliciaGarciaGarcia commented on modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/display/context/KBAdminManagementToolbarDisplayContext.java
>  			creationMenu.addDropdownItem(
This code is duplicated?

2022-07-07 08:24 UTC, AliciaGarciaGarcia commented
ci:test:sf

2022-07-07 08:24 UTC, AliciaGarciaGarcia commented
ci:test:relevant

2022-07-07 08:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/1542/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1542/jenkins-report.html">here</a>.</b></p>

2022-07-07 08:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6060b323abbae0fe362746d41395053fa847446f">6060b323abbae0fe362746d41395053fa847446f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/adolfopa/liferay-portal/tree/LPS-157078">LPS-157078</a><br/>Branch GIT ID: <a href="https://github.com/adolfopa/liferay-portal/commit/2b13278485ed052a9ff86893045c0a433a92c2d1">2b13278485ed052a9ff86893045c0a433a92c2d1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1542/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1542/jenkins-report.html">here</a>.</h5></details></html>

2022-07-07 08:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1542/">test-portal-source-format#1542</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1542/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3209">liferay-lima#3209</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1898990456">[master] ci:test:sf - adolfopa &gt; liferay-lima - PR#3209 - 2022-07-07[01:24:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/4910/">publish-testray-report#4910</a><br/></div></div>

2022-07-07 08:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2115/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2115/jenkins-report.html">here</a>.</b></p>

2022-07-07 10:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 48 out of 49 jobs passed in 1 hour 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6060b323abbae0fe362746d41395053fa847446f">6060b323abbae0fe362746d41395053fa847446f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ff72a17ea61cf3260c8a526e3d8b2904e09f5623">ff72a17ea61cf3260c8a526e3d8b2904e09f5623</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3513">Acceptance Upstream DXP (master) #3513</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44397/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/33518/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/45579/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43977/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43979/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41188/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37472/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39711/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37473/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87450/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102759/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41187/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39215/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43978/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/33517/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94725/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43980/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55071/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87452/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102968/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/42213/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94726/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106008/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36949/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43981/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37727/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 47 out of 49 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2115/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106009/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>47 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37471/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46729/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40454/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44397/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39710/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40455/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/42212/">functional-tomcat90-mysql57-jdk8/0/1</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/100924/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87900/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102967/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87451/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-t [...]

2022-07-07 10:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2115/">test-portal-acceptance-pullrequest(master)#2115</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2115/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3209">liferay-lima#3209</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1898996319">[master] ci:test:relevant - adolfopa &gt; liferay-lima - PR#3209 - 2022-07-07[01:55:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/4919/">publish-testray-report#4919</a><br/></div></div>

2022-07-07 11:09 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-07 11:11 UTC, closed without merging