[TS][SDH] LPS-164769 Avoid NPE when open notification has deleted user or layout.
liferay-lima/liferay-portal pull request #3558
Opened 2022-10-06 03:22 UTC by binhtran92

Hi team,
I'm supporting the ticket: https://issues.liferay.com/browse/LPP-46699 This is an SDH ticket. 
Please help me to review it.
Thank you.

2022-10-06 03:22 UTC, liferay-lima commented
ci:test:sf

2022-10-06 03:22 UTC, liferay-lima commented
ci:test:relevant

2022-10-06 03:22 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-06 03:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/4902/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4902/jenkins-report.html">here</a>.</b></p>

2022-10-06 03:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3095/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3095/jenkins-report.html">here</a>.</b></p>

2022-10-06 03:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b446a7e2ef08647ff87005ac81dfc5b385ba9a20">b446a7e2ef08647ff87005ac81dfc5b385ba9a20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/binhtran92/liferay-portal/tree/LPS-164769">LPS-164769</a><br/>Branch GIT ID: <a href="https://github.com/binhtran92/liferay-portal/commit/c5e647f04e4f116f201e4465f94f637e1fdc73d9">c5e647f04e4f116f201e4465f94f637e1fdc73d9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3095/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3095/jenkins-report.html">here</a>.</h5><pre>     [exec] Generating types (25 of 25): @liferay/object-web
     [exec] 
     [exec] ***************
     [exec] *** WARNING ***
     [exec] ***************
     [exec] 
     [exec] Out-of-date TypeScript build artifacts at:
     [exec] 
     [exec]     apps/object/object-web/types
     [exec] 
     [exec] Please commit them.
     [exec] 
     [exec] M modules/apps/object/object-web/types/src/main/resources/META-INF/resources/js/components/ObjectField/useObjectFieldForm.d.ts
     [exec] 
     [exec] Preflight check failed:
     [exec] checkTypeScriptTypeArtifacts() failed: Error: Type generation was successful but 2 projects were out of date. Please commit updated versions of the artifacts in the projects listed above.
     [exec] 
     [exec] Prettier checked 2 files
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2022-10-06 03:27:20.210.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2022-10-05-20-25-06.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2022-10-06 03:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3095/">test-portal-source-format#3095</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3095/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1998718363">[master] ci:test:sf - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-05[20:22:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/11517/">publish-testray-report#11517</a><br/></div></div>

2022-10-06 06:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/426/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/426/jenkins-report.html">here</a>.</b></p>

2022-10-06 06:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c33435613651a106b336a4d4bfa3dece7f5f139">7c33435613651a106b336a4d4bfa3dece7f5f139</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/binhtran92/liferay-portal/tree/LPS-164769">LPS-164769</a><br/>Branch GIT ID: <a href="https://github.com/binhtran92/liferay-portal/commit/c5e647f04e4f116f201e4465f94f637e1fdc73d9">c5e647f04e4f116f201e4465f94f637e1fdc73d9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/426/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/426/jenkins-report.html">here</a>.</h5><pre>     [exec] Generating types (25 of 25): @liferay/object-web
     [exec] 
     [exec] ***************
     [exec] *** WARNING ***
     [exec] ***************
     [exec] 
     [exec] Out-of-date TypeScript build artifacts at:
     [exec] 
     [exec]     apps/object/object-web/types
     [exec] 
     [exec] Please commit them.
     [exec] 
     [exec] M modules/apps/object/object-web/types/src/main/resources/META-INF/resources/js/components/ObjectField/useObjectFieldForm.d.ts
     [exec] 
     [exec] Preflight check failed:
     [exec] checkTypeScriptTypeArtifacts() failed: Error: Type generation was successful but 2 projects were out of date. Please commit updated versions of the artifacts in the projects listed above.
     [exec] 
     [exec] Prettier checked 2 files
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2022-10-06 06:11:54.618.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2022-10-05-23-09-24.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2022-10-06 06:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/426/">test-portal-source-format#426</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/426/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1998791700">[master] ci:test:sf - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-05[23:06:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/1376/">publish-testray-report#1376</a><br/></div></div>

2022-10-06 06:24 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.RuntimeException: Unable to create build anchor element. The process timed out while waiting for a build result for null.
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b446a7e2ef08647ff87005ac81dfc5b385ba9a20">b446a7e2ef08647ff87005ac81dfc5b385ba9a20</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/4902/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4902/jenkins-report.html">here</a>.</b></p>

2022-10-06 06:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/4902/">test-portal-acceptance-pullrequest(master)#4902</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4902/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1998796846">[master] ci:test:relevant - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-05[20:22:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/12424/">publish-testray-report#12424</a><br/></div></div>

2022-10-06 07:34 UTC, AliciaGarciaGarcia requested changes

2022-10-06 07:34 UTC, AliciaGarciaGarcia commented on modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_metadata/metadata_entry.jsp
> +			assetRendererUser = UserLocalServiceUtil.getUser(assetRenderer.getUserId());
If we will do nothing on the exception.
It not better idea to use the `fetch` methods?

2022-10-06 07:34 UTC, AliciaGarciaGarcia commented on modules/apps/portal-workflow/portal-workflow-task-web/src/main/resources/META-INF/resources/edit_workflow_task.jsp
> +			assetEntry = assetRendererFactory.getAssetEntry(workflowHandler.getClassName(), assetRenderer.getClassPK());
`assetRenderer` can be null here as you put before?

And we are trying to access to her values?

Checking null maybe it's needed?

2022-10-06 07:43 UTC, binhtran92 commented on modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_metadata/metadata_entry.jsp
> +		}
@adolfopa : Thank you for reviewing, I will update the change.

2022-10-06 08:46 UTC, binhtran92 commented
Hi @adolfopa @AliciaGarciaGarcia,
Thank you for reviewing, I updated the change.

2022-10-06 09:14 UTC, binhtran92 commented
ci:test:sf

2022-10-06 09:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3323/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3323/jenkins-report.html">here</a>.</b></p>

2022-10-06 09:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c33435613651a106b336a4d4bfa3dece7f5f139">7c33435613651a106b336a4d4bfa3dece7f5f139</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/binhtran92/liferay-portal/tree/LPS-164769">LPS-164769</a><br/>Branch GIT ID: <a href="https://github.com/binhtran92/liferay-portal/commit/1bf9688fde449ce9a369ff12acaa6874ba25d4f8">1bf9688fde449ce9a369ff12acaa6874ba25d4f8</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3323/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3323/jenkins-report.html">here</a>.</h5><pre>     [exec] Generating types (17 of 25): frontend-js-tabs-support-web
     [exec] Generating types (18 of 25): frontend-js-tooltip-support-web
     [exec] Generating types (19 of 25): item-selector-taglib
     [exec] Generating types (20 of 25): layout-admin-web
     [exec] Generating types (21 of 25): @liferay/notification-web
     [exec] Generating types (22 of 25): @liferay/oauth2-provider-web
     [exec] Generating types (23 of 25): @liferay/object-dynamic-data-mapping-form-field-type
     [exec] Generating types (24 of 25): @liferay/object-js-components-web
     [exec] Generating types (25 of 25): @liferay/object-web
     [exec] 
     [exec] ***************
     [exec] *** WARNING ***
     [exec] ***************
     [exec] 
     [exec] Out-of-date TypeScript build artifacts at:
     [exec] 
     [exec]     apps/object/object-web/types
     [exec] 
     [exec] Please commit them.
     [exec] 
     [exec] M modules/apps/object/object-web/types/src/main/resources/META-INF/resources/js/components/ObjectField/useObjectFieldForm.d.ts
     [exec] 
     [exec] Preflight check failed:
     [exec] checkTypeScriptTypeArtifacts() failed: Error: Type generation was successful but 2 projects were out of date. Please commit updated versions of the artifacts in the projects listed above.
     [exec] 
     [exec] Prettier checked 1 file
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2022-10-06 09:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3323/">test-portal-source-format#3323</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3323/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1999700056">[master] ci:test:sf - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-06[02:14:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/12862/">publish-testray-report#12862</a><br/></div></div>

2022-10-06 09:50 UTC, adolfopa requested changes

2022-10-06 09:50 UTC, adolfopa commented on modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/asset/model/LayoutAssetRendererFactory.java
> +
This looks wrong. If the user doesn't exist, the assetEntry will be partially updated. If the user is null, you should do something like this:
```
if (user != null) {
    ...
}
else {
    assetEntry.setCompanyId(layout.getCompanyId());
    assetEntry.setUserId(_userLocalService.getDefaultUserId(layout.getCompanyId());
    ...
}
```

2022-10-07 06:48 UTC, sontruongces commented
@adolfopa, Can you please take a look at the fix based on Binh's update? The customer needs the fix to Go-live so we want your approval for the fix so we can delivery it to them ASAP. Thanks!

2022-10-07 07:07 UTC, adolfopa approved these changes

2022-10-07 08:55 UTC, AliciaGarciaGarcia commented
ci:test:sf

2022-10-07 08:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/525/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/525/jenkins-report.html">here</a>.</b></p>

2022-10-07 08:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/410123945a2bd55e8d58aa8e0baf51cd2235e4d0">410123945a2bd55e8d58aa8e0baf51cd2235e4d0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/binhtran92/liferay-portal/tree/LPS-164769">LPS-164769</a><br/>Branch GIT ID: <a href="https://github.com/binhtran92/liferay-portal/commit/e9a99db600b6b90351672a8680e48463b0614d28">e9a99db600b6b90351672a8680e48463b0614d28</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/525/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/525/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/asset/model/LayoutAssetRendererFactory.java expected:&lt;...ce.fetchDefaultUser([]layout.getCompanyId(...&gt; but was:&lt;...ce.fetchDefaultUser([
     [java]         ]layout.getCompanyId(...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:02.891 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-39/job/test-portal-source-format/525//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221007015840147.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221007015840147.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2112024964.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1047642431
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 261ms
[junitreport] Deleting: /tmp/null1047642431
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-07-2022 01:58:42:870 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2022-10-07 09:15 UTC, adolfopa commented
@binhtran92 Please fix the sf error. Before pushing changes, remember to always run source format in you local branch.

2022-10-07 09:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/689/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/689/jenkins-report.html">here</a>.</b></p>

2022-10-07 09:27 UTC, sontruongces commented
> @binhtran92 Please fix the sf error. Before pushing changes, remember to always run source format in you local branch.

@adolfopa , Binh is out of the office from today to next Monday. So I'm not sure that he can update it. So please wait for his update when he is back. If there is anything that I can help please just let me know. Thanks!

2022-10-07 09:36 UTC, AliciaGarciaGarcia approved these changes
LGTM > SF failures relevant to this PR

2022-10-07 09:36 UTC, AliciaGarciaGarcia commented
ci:stop

2022-10-07 09:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 22 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/410123945a2bd55e8d58aa8e0baf51cd2235e4d0">410123945a2bd55e8d58aa8e0baf51cd2235e4d0</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f38b8f8b5d34f78d0cd36ce61343d20bdda6786a">f38b8f8b5d34f78d0cd36ce61343d20bdda6786a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2000462772">EE Development Acceptance (master) - 3878 - 2022-10-06[20:39:49]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/689/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/689/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/689/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-10-07 10:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/525/">test-portal-source-format#525</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/525/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2000603617">[master] ci:test:sf - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-07[01:55:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/1633/">publish-testray-report#1633</a><br/></div></div>

2022-10-07 11:07 UTC, adolfopa commented
@sontruongces If you could fetch this branch, rebase, run auto sf, add an extra SF commit and push-force it here (or send a new pr if you don't have permissions) we'd be eternally grateful :-) Right now we're working on other branches, so it's a bit of a pain for us.

2022-10-07 11:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/689/">test-portal-acceptance-pullrequest(master)#689</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/689/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2000620580">[master] ci:test:relevant - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-07[02:16:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/1646/">publish-testray-report#1646</a><br/></div></div>

2022-10-09 13:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3352/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3352/jenkins-report.html">here</a>.</b></p>

2022-10-09 13:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/842b65008c4855399d8e1cf41799d123561f573d">842b65008c4855399d8e1cf41799d123561f573d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/binhtran92/liferay-portal/tree/LPS-164769">LPS-164769</a><br/>Branch GIT ID: <a href="https://github.com/binhtran92/liferay-portal/commit/76746e05da981d1a6bca7929a3838fe92d6cdcdf">76746e05da981d1a6bca7929a3838fe92d6cdcdf</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3352/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3352/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/asset/model/LayoutAssetRendererFactory.java expected:&lt;...ce.fetchDefaultUser([]layout.getCompanyId(...&gt; but was:&lt;...ce.fetchDefaultUser([
     [java]         ]layout.getCompanyId(...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:10.169 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-37/job/test-portal-source-format/3352//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221009060153692.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221009060153692.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null773910090.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1242740618
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 217ms
[junitreport] Deleting: /tmp/null1242740618
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-09-2022 06:01:56:150 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2022-10-09 13:02 UTC, binhtran92 commented
ci:test:sf

2022-10-09 13:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/3437/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/3437/jenkins-report.html">here</a>.</b></p>

2022-10-09 13:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/842b65008c4855399d8e1cf41799d123561f573d">842b65008c4855399d8e1cf41799d123561f573d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/binhtran92/liferay-portal/tree/LPS-164769">LPS-164769</a><br/>Branch GIT ID: <a href="https://github.com/binhtran92/liferay-portal/commit/76746e05da981d1a6bca7929a3838fe92d6cdcdf">76746e05da981d1a6bca7929a3838fe92d6cdcdf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/3437/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/3437/jenkins-report.html">here</a>.</h5></details></html>

2022-10-09 13:09 UTC, binhtran92 commented
ci:test:relevant

2022-10-09 13:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4908/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4908/jenkins-report.html">here</a>.</b></p>

2022-10-09 13:10 UTC, binhtran92 commented
Hi guys, thank you for helping me with this PR. I updated the new SF.

2022-10-09 13:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/3437/">test-portal-source-format#3437</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/3437/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2001975461">[master] ci:test:sf - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-09[06:02:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/12500/">publish-testray-report#12500</a><br/></div></div>

2022-10-09 14:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 213 out of 222 jobs passed in 1 hour 43 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/842b65008c4855399d8e1cf41799d123561f573d">842b65008c4855399d8e1cf41799d123561f573d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/928f7e0fb98b8dcf2b03ec6eb14cfc7a18682ea2">928f7e0fb98b8dcf2b03ec6eb14cfc7a18682ea2</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2001721893">EE Development Acceptance (master) - 3880 - 2022-10-08[07:36:48]</a></p><details><summary><strong>ci:test:stable - 28 out of 28 jobs PASSED</strong></summary><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 212 out of 222 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4908/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258380/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50910/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258375/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266092/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/100339/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/252526/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/242469/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273568/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/252516/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208865/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/242475/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255629/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258377/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/282271/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263476/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/268997/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266094/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266088/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263470/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50902/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/242470/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266089/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/268992/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228404/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/252519/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233124/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208868/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255632/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/242478/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266097/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269000/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263479/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258373/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/282267/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/282268/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273565/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50903/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263472/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263473/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/268994/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://t [...]

2022-10-09 14:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4908/">test-portal-acceptance-pullrequest(master)#4908</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4908/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3558">liferay-lima#3558</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2001992640">[master] ci:test:relevant - binhtran92 &gt; liferay-lima - PR#3558 - 2022-10-09[06:09:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/12275/">publish-testray-report#12275</a><br/></div></div>

2022-10-10 07:49 UTC, adolfopa commented
ci:forward

2022-10-10 07:49 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-10-10 07:49 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-10-10 07:51 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/596//consoleFull)

2022-10-10 07:52 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/124288
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/596//consoleFull)

2022-10-10 07:52 UTC, closed without merging