LPS-162714 | Automate LPS-159876
liferay-lima/liferay-portal pull request #3790
Opened 2022-11-30 12:51 UTC by jaimelr10

Description: Creation of Priority 4 test to verify that Friendly URL is not escaped when it has certain characters as described in [LPS-159876](https://issues.liferay.com/browse/LPS-159876)

Jira Ticket: https://issues.liferay.com/browse/LPS-162714

2022-11-30 12:51 UTC, liferay-lima commented
ci:test:sf

2022-11-30 12:51 UTC, liferay-lima commented
ci:test:relevant

2022-11-30 12:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-30 12:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/5028/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5028/jenkins-report.html">here</a>.</b></p>

2022-11-30 12:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c9ef524b20784300278e77c280e372a674ae71cf">c9ef524b20784300278e77c280e372a674ae71cf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaimelr10/liferay-portal/tree/LPS-162714">LPS-162714</a><br/>Branch GIT ID: <a href="https://github.com/jaimelr10/liferay-portal/commit/45b280652cdcd2d49ff67d8f7e7af0fa68778107">45b280652cdcd2d49ff67d8f7e7af0fa68778107</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5028/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5028/jenkins-report.html">here</a>.</h5></details></html>

2022-11-30 12:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5028/">test-portal-source-format#5028</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5028/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2089323509">[master] ci:test:sf - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-11-30[04:51:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/18032/">publish-testray-report#18032</a><br/></div></div>

2022-11-30 13:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6664/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6664/jenkins-report.html">here</a>.</b></p>

2022-11-30 13:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6664/">test-portal-acceptance-pullrequest(master)#6664</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6664/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2089323870">[master] ci:test:relevant - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-11-30[05:02:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15490/">publish-testray-report#15490</a><br/></div></div>

2022-12-02 03:04 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/sites/friendlyurl/FriendlyURL.testcase
> +	@description = "This is a test for LPS-162714. Checks that Web Content FriendlyURL is not displayed escaped whit special characters like éöő"
"with special characters"

2022-12-02 03:05 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/sites/friendlyurl/FriendlyURL.testcase
> +	test WebContentURLNotEscaped {
Please change to **SpecialCharactersAreNotEscapedFromWebContentURL**

2022-12-02 03:06 UTC, austinchiang requested changes
Please resend with changes, thx

2022-12-02 09:43 UTC, jaimelr10 commented
ci:test:sf

2022-12-02 09:43 UTC, jaimelr10 commented
ci:test:relevant

2022-12-02 09:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6723/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6723/jenkins-report.html">here</a>.</b></p>

2022-12-02 09:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1387/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1387/jenkins-report.html">here</a>.</b></p>

2022-12-02 09:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6723/">test-portal-acceptance-pullrequest(master)#6723</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6723/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2095268437">[master] ci:test:relevant - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-12-02[01:43:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15594/">publish-testray-report#15594</a><br/></div></div>

2022-12-02 09:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1387/">test-portal-source-format#1387</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1387/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2095268799">[master] ci:test:sf - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-12-02[01:43:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4622/">publish-testray-report#4622</a><br/></div></div>

2022-12-05 07:20 UTC, jaimelr10 commented
ci:test:sf

2022-12-05 07:21 UTC, jaimelr10 commented
ci:test:relevant

2022-12-05 07:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5637/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5637/jenkins-report.html">here</a>.</b></p>

2022-12-05 07:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1403/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1403/jenkins-report.html">here</a>.</b></p>

2022-12-05 07:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/201f3d3fec59d2ea77f7773a4ea2a513c779962d">201f3d3fec59d2ea77f7773a4ea2a513c779962d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaimelr10/liferay-portal/tree/LPS-162714">LPS-162714</a><br/>Branch GIT ID: <a href="https://github.com/jaimelr10/liferay-portal/commit/ec8a1c58c94a3786f064b155ec6b40de50aaf0d0">ec8a1c58c94a3786f064b155ec6b40de50aaf0d0</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1403/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1403/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/sites/friendlyurl/FriendlyURL.testcase expected:&lt;...iption = "This is a [test for LPS-162714. Checks that Web Content FriendlyURL special characters like ?????? are not escaped"
     [java]   @priority = "4"
     [java]   test SpecialCharactersAreNotEscapedFromWebContentURL \{
     [java]     JSONWebcontent.addWebContent(
     [java]       content = "WC WebContent Content",
     [java]       groupName = "Test Site Name",
     [java]       title = "??????");
     [java] 
     [java]     WebContentNavigator.openWebContentAdmin(siteURLKey = "test-site-name");
     [java] 
     [java]     WebContentNavigator.gotoEditCP(webContentTitle = "??????");
     [java] 
     [java]     WebContent.viewFriendlyURLCP(friendlyURL = "eoo");
     [java]   \}
     [java] 
     [java]   @description = "This is a use case for LPS-161024. Verify uppercase virtual host names added to a site's url are converted to lowercase."
     [java]   @priority = "3"
     [java]   test UppercaseVirtualHostNamesConvertedToLowercase \{
     [java]     property test.name.skip.portal.instance = "FriendlyURL#UppercaseVirtualHostNamesConvertedToLowercase";
     [java] 
     [java]     task ("When an uppercase virtual host is added to a site url") \{
     [java]       Site.openSiteSettingsAdmin(siteURLKey = "test-site-name");
     [java] 
     [java]       Site.addVirtualHostsURLCP(
     [java]         pageVirtualHosts = "true",
     [java]         pageVirtualHostURL = "LIFERAY-UPPER");
     [java]     \}
     [java] 
     [java]     task ("Then the virtual host gets converted to lowercase in the database") \{
     [java]       var virtualHostQueryResult = SQL.executeMySQLStatement(mysqlStatement = "SELECT * FROM lportal.VirtualHost;");
     [java] 
     [java]       if (contains("\$\{virtualHostQueryResult\}", "LIFERAY-UPPER") || !(contains("\$\{virtualHostQueryResult\}", "liferay-upper"))) \{
     [java]         echo("\$\{virtualHostQueryResult\}");
     [java] 
     [java]         fail("The virtual host was not converted to lowercase");
     [java]       \}
     [java]     \}
     [java]   \}
     [java] 
     [java]   @priority = "4"
     [java]   test VerifyFriendlyURLsOnlyDisplayLocaleOnce \{
     [java]     JSONLayout.addPublicLayout(
     [java]       groupName = "Test Site Name",
     [java]       layoutName = "Test Page");
     [java] </pre></details></html>

2022-12-05 07:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1403/">test-portal-source-format#1403</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1403/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2101556542">[master] ci:test:sf - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-12-04[23:21:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4715/">publish-testray-report#4715</a><br/></div></div>

2022-12-05 07:26 UTC, jaimelr10 commented
ci:test:relevant

2022-12-05 07:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5641/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5641/jenkins-report.html">here</a>.</b></p>

2022-12-05 07:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5637/">test-portal-acceptance-pullrequest(master)#5637</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5637/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2101556570">[master] ci:test:relevant - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-12-04[23:21:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/14357/">publish-testray-report#14357</a><br/></div></div>

2022-12-05 07:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5641/">test-portal-acceptance-pullrequest(master)#5641</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5641/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2101610601">[master] ci:test:relevant - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-12-04[23:27:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13872/">publish-testray-report#13872</a><br/></div></div>

2022-12-06 07:24 UTC, austinchiang commented
ci:stop

2022-12-06 07:34 UTC, austinchiang commented
ci:test:sf

2022-12-06 07:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3770/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3770/jenkins-report.html">here</a>.</b></p>

2022-12-06 07:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a95abb9ce4c2f8da332355fa901d0d80d983b788">a95abb9ce4c2f8da332355fa901d0d80d983b788</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaimelr10/liferay-portal/tree/LPS-162714">LPS-162714</a><br/>Branch GIT ID: <a href="https://github.com/jaimelr10/liferay-portal/commit/ec8a1c58c94a3786f064b155ec6b40de50aaf0d0">ec8a1c58c94a3786f064b155ec6b40de50aaf0d0</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3770/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3770/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/sites/friendlyurl/FriendlyURL.testcase expected:&lt;...iption = "This is a [test for LPS-162714. Checks that Web Content FriendlyURL special characters like ?????? are not escaped"
     [java]   @priority = "4"
     [java]   test SpecialCharactersAreNotEscapedFromWebContentURL \{
     [java]     JSONWebcontent.addWebContent(
     [java]       content = "WC WebContent Content",
     [java]       groupName = "Test Site Name",
     [java]       title = "??????");
     [java] 
     [java]     WebContentNavigator.openWebContentAdmin(siteURLKey = "test-site-name");
     [java] 
     [java]     WebContentNavigator.gotoEditCP(webContentTitle = "??????");
     [java] 
     [java]     WebContent.viewFriendlyURLCP(friendlyURL = "eoo");
     [java]   \}
     [java] 
     [java]   @description = "This is a use case for LPS-161024. Verify uppercase virtual host names added to a site's url are converted to lowercase."
     [java]   @priority = "3"
     [java]   test UppercaseVirtualHostNamesConvertedToLowercase \{
     [java]     property test.name.skip.portal.instance = "FriendlyURL#UppercaseVirtualHostNamesConvertedToLowercase";
     [java] 
     [java]     task ("When an uppercase virtual host is added to a site url") \{
     [java]       Site.openSiteSettingsAdmin(siteURLKey = "test-site-name");
     [java] 
     [java]       Site.addVirtualHostsURLCP(
     [java]         pageVirtualHosts = "true",
     [java]         pageVirtualHostURL = "LIFERAY-UPPER");
     [java]     \}
     [java] 
     [java]     task ("Then the virtual host gets converted to lowercase in the database") \{
     [java]       var virtualHostQueryResult = SQL.executeMySQLStatement(mysqlStatement = "SELECT * FROM lportal.VirtualHost;");
     [java] 
     [java]       if (contains("\$\{virtualHostQueryResult\}", "LIFERAY-UPPER") || !(contains("\$\{virtualHostQueryResult\}", "liferay-upper"))) \{
     [java]         echo("\$\{virtualHostQueryResult\}");
     [java] 
     [java]         fail("The virtual host was not converted to lowercase");
     [java]       \}
     [java]     \}
     [java]   \}
     [java] 
     [java]   @priority = "4"
     [java]   test VerifyFriendlyURLsOnlyDisplayLocaleOnce \{
     [java]     JSONLayout.addPublicLayout(
     [java]       groupName = "Test Site Name",
     [java]       layoutName = "Test Page");
     [java] </pre></details></html>

2022-12-06 07:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3770/">test-portal-source-format#3770</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3770/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3790">liferay-lima#3790</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2104978927">[master] ci:test:sf - jaimelr10 &gt; liferay-lima - PR#3790 - 2022-12-05[23:34:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13903/">publish-testray-report#13903</a><br/></div></div>

2022-12-06 07:58 UTC, austinchiang commented
@jaimelr10 can you fix sf again and resend in a new pull? I'll close this one

2022-12-06 07:58 UTC, closed without merging