LPS-159900 | Master
liferay-lima/liferay-portal pull request #3795
Opened 2022-12-01 07:04 UTC by Jeremy-Ch

https://issues.liferay.com/browse/LPS-159900

2022-12-01 07:04 UTC, liferay-lima commented
ci:test:sf

2022-12-01 07:04 UTC, liferay-lima commented
ci:test:relevant

2022-12-01 07:04 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-01 07:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/6175/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6175/jenkins-report.html">here</a>.</b></p>

2022-12-01 07:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/4045/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4045/jenkins-report.html">here</a>.</b></p>

2022-12-01 07:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8567ab84e3ba352f600659394a4dee861a74cdaf">8567ab84e3ba352f600659394a4dee861a74cdaf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Jeremy-Ch/liferay-portal/tree/master-lps-159900">master-lps-159900</a><br/>Branch GIT ID: <a href="https://github.com/Jeremy-Ch/liferay-portal/commit/379e27aa38a606916056806128c2beddb58de178">379e27aa38a606916056806128c2beddb58de178</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4045/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4045/jenkins-report.html">here</a>.</h5></details></html>

2022-12-01 07:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/6175/">test-portal-acceptance-pullrequest(master)#6175</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6175/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3795">liferay-lima#3795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2091903938">[master] ci:test:relevant - Jeremy-Ch &gt; liferay-lima - PR#3795 - 2022-11-30[23:04:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/15097/">publish-testray-report#15097</a><br/></div></div>

2022-12-01 07:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4045/">test-portal-source-format#4045</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4045/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3795">liferay-lima#3795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2091903974">[master] ci:test:sf - Jeremy-Ch &gt; liferay-lima - PR#3795 - 2022-11-30[23:04:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15532/">publish-testray-report#15532</a><br/></div></div>

2022-12-02 01:42 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/macros/KBArticle.macro
> +	macro selectAssetsToDisplayOnWidget {
Can you select a folder? If article only please rename to selectArticlesToDisplayOnWidget for clarity

2022-12-02 01:43 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/macros/KBArticle.macro
> +	macro selectAssetsToDisplayOnWidget {
Oh nevermind I see https://github.com/liferay-lima/liferay-portal/pull/3795/commits/eff355a316b5f9fc0f8fa3ffbf479f71c02d39cf#diff-69c24ae27b612c28e85d0563fecaecb9cbd92e269ca87140fb38a2bf02604c7fR887-R892 now

2022-12-02 01:44 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/macros/KBArticle.macro
> +		if (isSet(viewSectionsInModal)) {
change to viewOpenSectionsInModal

2022-12-02 01:45 UTC, austinchiang requested changes
Please make changes and resend

2022-12-02 02:59 UTC, Jeremy-Ch commented
ci:test:sf

2022-12-02 03:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1384/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1384/jenkins-report.html">here</a>.</b></p>

2022-12-02 03:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b69bd6a04fa27629d64448389d92bf7743e4b008">b69bd6a04fa27629d64448389d92bf7743e4b008</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Jeremy-Ch/liferay-portal/tree/master-lps-159900">master-lps-159900</a><br/>Branch GIT ID: <a href="https://github.com/Jeremy-Ch/liferay-portal/commit/fbb5fa3e93fd8c09f2d9d7931d27d6f7f7e9d4ab">fbb5fa3e93fd8c09f2d9d7931d27d6f7f7e9d4ab</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1384/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1384/jenkins-report.html">here</a>.</h5></details></html>

2022-12-02 03:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1384/">test-portal-source-format#1384</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1384/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3795">liferay-lima#3795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2094777882">[master] ci:test:sf - Jeremy-Ch &gt; liferay-lima - PR#3795 - 2022-12-01[18:59:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4607/">publish-testray-report#4607</a><br/></div></div>

2022-12-02 03:15 UTC, austinchiang approved these changes

2022-12-02 03:15 UTC, austinchiang commented
ci:forward

2022-12-02 03:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-12-02 03:16 UTC, closed without merging