LPS-169410 | master
liferay-lima/liferay-portal pull request #3832
Opened 2022-12-08 06:28 UTC by Hanlf

https://issues.liferay.com/browse/LPS-169410

@austinchiang and @david-gutierrez-mesa 
There are some modules involving the **asset library** and **site**, such as StructuredContent and Language.
I divided the headless tests according to whether the API is **assetLibraries** related: 
For example, `getAssetLibraryStructuredContentsPage` is under the StructuredContent module, but it is assetLibraries related, then I moved the test to Lima.
Another example, `getAssetLibraryLanguagesPage` is under the Language module, it is related to assetLibraries, I moved it to Lima as well.
Please let me know what you think, thanks

2022-12-08 06:28 UTC, liferay-lima commented
ci:test:relevant

2022-12-08 06:28 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-08 06:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/5109/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5109/jenkins-report.html">here</a>.</b></p>

2022-12-08 06:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5697bc6c998f95e8803c32bda4ad5582f52b2786">5697bc6c998f95e8803c32bda4ad5582f52b2786</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hanlf/liferay-portal/tree/master-lps-169410">master-lps-169410</a><br/>Branch GIT ID: <a href="https://github.com/Hanlf/liferay-portal/commit/43840eab55fd2f75a3efea57e672fc247c1eb201">43840eab55fd2f75a3efea57e672fc247c1eb201</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5109/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5109/jenkins-report.html">here</a>.</h5></details></html>

2022-12-08 06:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5109/">test-portal-source-format#5109</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5109/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3832">liferay-lima#3832</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2110323213">[master] ci:test:sf - Hanlf &gt; liferay-lima - PR#3832 - 2022-12-07[22:28:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/18315/">publish-testray-report#18315</a><br/></div></div>

2022-12-08 06:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6299/">test-portal-acceptance-pullrequest(master)#6299</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6299/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3832">liferay-lima#3832</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2110324825">[master] ci:test:relevant - Hanlf &gt; liferay-lima - PR#3832 - 2022-12-07[22:29:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/15906/">publish-testray-report#15906</a><br/></div></div>

2022-12-09 07:06 UTC, austinchiang commented
@Hanlf My opinion is that we should sort these files based on what the primary test object is, not what the secondary or tertiary test factors are. In the case of `getAssetLibraryStructuredContentsPage` you're primarily testing a (web content) structure which happens to be in an asset library so I think it can belong to echo. The same goes for `getAssetLibraryLanguagesPage`; since the language component is owned by Echo I think it's best they own it. Without looking at the code I'm fairly certain asset libraries/sites both use the same or similar language framework which is owned by Echo.

LMK what you think @david-gutierrez-mesa, I think we'll need to draw some lines here

2022-12-09 08:13 UTC, david-gutierrez-mesa commented
Hi there! I agree with @austinchiang . We should place the test based on the primary objective. So feel free to assign them to Echo. @austinchiang just to add that you should check if you would need to add some of the components where we are moving these tests to Lima modules in order to be executed on your PR. But that's up to you.

2022-12-19 02:53 UTC, austinchiang commented
Converting to draft until progress is made

2022-12-28 07:42 UTC, Hanlf commented
Hi @david-gutierrez-mesa 
Based on the primary test object, I left these three tests to Echo, thanks!
`ExposeErcFromAssetLibraryForStructuredContentFolders.testcase`
`ExposeErcFromAssetLibraryForStructuredContents.testcase`
`ExposeLanguagesFromAssetLibraryAndSite.testcase`
cc/ @austinchiang

2023-01-04 06:07 UTC, austinchiang commented on modules/apps/headless/headless-delivery/headless-delivery-test/src/testFunctional/tests/HeadlessDeliverySupportDifferentParameters.testcase
> +	property testray.main.component.name = "Lima Headless";
There are a few tests here that belong to Echo. Please find them and reclassify them

2023-01-04 06:09 UTC, austinchiang requested changes
Please make changes and resend @Hanlf

2023-01-11 10:42 UTC, Hanlf commented
@david-gutierrez-mesa Another test(HeadlessDeliverySupportDifferentParameters.testcase) is left to your team, thanks!
@austinchiang Regarding the names of the test cases, I'll try to keep them as they are, and I'll update them if needed when I have a better understanding of the tests.

2023-01-12 05:07 UTC, austinchiang approved these changes
LGTM

2023-01-12 05:07 UTC, austinchiang commented
ci:forward

2023-01-12 05:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-01-12 05:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/2251/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2251/jenkins-report.html">here</a>.</b></p>

2023-01-12 05:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/1922/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1922/jenkins-report.html">here</a>.</b></p>

2023-01-12 05:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/045dfcd7cf0f5630008e30b11e4694570adea96a">045dfcd7cf0f5630008e30b11e4694570adea96a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hanlf/liferay-portal/tree/master-lps-169410">master-lps-169410</a><br/>Branch GIT ID: <a href="https://github.com/Hanlf/liferay-portal/commit/f103227f9dd108eecd8a451251e7bef38cad483f">f103227f9dd108eecd8a451251e7bef38cad483f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1922/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1922/jenkins-report.html">here</a>.</h5></details></html>

2023-01-12 05:10 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/test-portal-source-format/1922//consoleFull)

2023-01-12 05:11 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/128647
[Console](https://test-1-35.liferay.com/job/test-portal-source-format/1922//consoleFull)

2023-01-12 05:11 UTC, closed without merging

2023-01-12 05:11 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/128647

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/2251//consoleFull)

2023-01-12 05:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1922/">test-portal-source-format#1922</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1922/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3832">liferay-lima#3832</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2158597996">[master] ci:test:sf - Hanlf &gt; liferay-lima - PR#3832 - 2023-01-11[21:07:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/7580/">publish-testray-report#7580</a><br/></div></div>

2023-01-12 05:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/2251/">test-portal-acceptance-pullrequest(master)#2251</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2251/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3832">liferay-lima#3832</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2158598008">[master] ci:test:relevant - Hanlf &gt; liferay-lima - PR#3832 - 2023-01-11[21:07:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/5335/">publish-testray-report#5335</a><br/></div></div>