LPS-157175 | Automate LPS-148397
liferay-lima/liferay-portal pull request #3859
Opened 2022-12-19 15:24 UTC by jaimelr10

Description: Creation of Priority 3 test to verify that when we download a zip file with a given structure, and we unzip it, there are no corrupted filenames as described in [LPS-148397](https://issues.liferay.com/browse/LPS-148397)

Jira Ticket: https://issues.liferay.com/browse/LPS-157175

2022-12-19 15:24 UTC, liferay-lima commented
ci:test:sf

2022-12-19 15:24 UTC, liferay-lima commented
ci:test:relevant

2022-12-19 15:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5837/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5837/jenkins-report.html">here</a>.</b></p>

2022-12-19 15:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3835/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3835/jenkins-report.html">here</a>.</b></p>

2022-12-19 15:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5837/">test-portal-acceptance-pullrequest(master)#5837</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5837/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3859">liferay-lima#3859</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2134331707">[master] ci:test:relevant - jaimelr10 &gt; liferay-lima - PR#3859 - 2022-12-19[07:24:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/14814/">publish-testray-report#14814</a><br/></div></div>

2022-12-19 15:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e12eff197f0acddcb6eadbc8def71ca1ecb37013">e12eff197f0acddcb6eadbc8def71ca1ecb37013</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaimelr10/liferay-portal/tree/LPS-157175">LPS-157175</a><br/>Branch GIT ID: <a href="https://github.com/jaimelr10/liferay-portal/commit/1946d96dacf27c56927257eb39f012ffd9085d4f">1946d96dacf27c56927257eb39f012ffd9085d4f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3835/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3835/jenkins-report.html">here</a>.</h5></details></html>

2022-12-19 15:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3835/">test-portal-source-format#3835</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3835/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/3859">liferay-lima#3859</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2134333526">[master] ci:test:sf - jaimelr10 &gt; liferay-lima - PR#3859 - 2022-12-19[07:26:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/14149/">publish-testray-report#14149</a><br/></div></div>

2022-12-20 01:00 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/macros/DMFolder.macro
> +			portlet = "Documents and Media");
This isn't needed in the macro. If you need to refresh the UI before clicking on the folder ellipsis you can use the Refresh function at the test case level to do it

2022-12-20 01:25 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/macros/DMFolder.macro
> +			locator1 = "DocumentsAndMedia#FOLDER_ELLIPSIS");
Can you reuse Icon#ROW_VERTICAL_ELLIPSIS here? you would just need to declare the folder name

2022-12-20 01:41 UTC, austinchiang requested changes

2022-12-20 01:41 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/documentsadministration/DMFileEntry.testcase
> +			dmDocumentTitle = "Document_2.doc");
Please use existing JSON macros for these

2022-12-20 01:41 UTC, austinchiang commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/documentsadministration/DMFileEntry.testcase
> +		}
Please move into a macro and make it reusable

2022-12-22 12:12 UTC, closed without merging