LPS-180298 POC: Manage multiple store areas in DLStore
liferay-lima/liferay-portal pull request #4196
Opened 2023-04-11 12:26 UTC by marcogalluzzi

This is a proposal for the implementation of multiple store areas (I think the term _area_ is better than _space_). The first idea was to set thread locally the read and write areas, to avoid doing many changes. However, the concept of an _area_ should be included in every class implementing the `Store` interface, otherwise we could not change, for instance, the `rootDir` of an `FileSystemStore`. So, if we have to finally change the stores, I would add the _area_ as a parameter for all `Store` methods. In order to avoid many changes at first, I've added an intermediate interface called `AreaStore` that is only implemented by the `FileSystemStore`. All stores that want to use the _areas_ will end implementing the `AreaStore`: if all, then we could simply end changing the `Store` interface and remove the `AreaStore` interface.

Finally, in class `DLStoreImpl` I've just implemented an example of how the deletion should be done using the new `StoreArea`, there are still operations missing.

### Open questions

`FileSystemStoreRegister.acivate()` and `AdvancedFileSystemStoreRegister.activate()` register the service with parameter `rootDir`. Currently we are passing only the `AreaType.LIVE` root folder. I think this parameter is only used by the `AntivirusAsyncFileStoreMessageListener` to do the Antivirus working on the root folder. Should we pass to the Antivirus also the root folders `AreaType.EVICTED` and `AreaType.DELETED` ?

I think we should change the service `CTSContentLocalService` updated in class `CTStore` to include the `areaType` or we have to update it only when `AreaType.LIVE` is touched ?

2023-04-11 12:26 UTC, liferay-lima commented
ci:test:sf

2023-04-11 12:26 UTC, liferay-lima commented
ci:test:relevant

2023-04-11 12:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-11 13:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/7661/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7661/jenkins-report.html">here</a>.</b></p>

2023-04-11 13:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2d5b39b2583dc4cc5c7dbe8f55d7cc074d7ce17f">2d5b39b2583dc4cc5c7dbe8f55d7cc074d7ce17f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bf858c537513dd97f0ea646d19ba36cd5ebb175c">bf858c537513dd97f0ea646d19ba36cd5ebb175c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2262423948">EE Development Acceptance (master) - 4449 - 2023-04-08[13:00:56]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/7661/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7661/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/7661/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/liferay-lima/liferay-portal/pull/4196">marcogalluzzi/subtask/LPS-180298_multiple_store_areas</a></strong><pre>Target exception: java.lang.RuntimeException: Unable to rebase master-temp-1681219276369 to master
Rebasing (1/3)
error: could not apply 75d1bd6c2194... LPS-180298 Added intermediate interface AreaStore, everything still works as before
Resolve all conflicts manually, mark them as resolved with
"git add/rm &lt;conflicted_files&gt;", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 75d1bd6c2194... LPS-180298 Added intermediate interface AreaStore, everything still works as before</pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-04-13 14:12 UTC, adolfopa requested changes
@marcogalluzzi I'm not sure about this, this is a very big API change. As this affects an component that we don't own we'll need to speak with core infrastructure, show them both approaches and let them decide.

2023-04-13 14:16 UTC, adolfopa commented on modules/apps/portal-store/portal-store-file-system/src/main/java/com/liferay/portal/store/file/system/FileSystemStore.java
> +		return _rootDirs.get(areaType);
Another thing to take into account is that the root dir is an implementation detail of the filesystem store. In other stores there is no concept of root dir. The current approach for the AreaType may not work for other stores.

2023-05-08 16:26 UTC, closed without merging