LPS-181652 Can't see Knowledge Base Article Child when Parent Article still pending
liferay-lima/liferay-portal pull request #4229
Opened 2023-04-18 15:40 UTC by manuelecastro

2023-04-18 15:41 UTC, liferay-lima commented
ci:test:sf

2023-04-18 15:41 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-18 15:41 UTC, liferay-lima commented
ci:test:relevant

2023-04-18 15:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5113/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5113/jenkins-report.html">here</a>.</b></p>

2023-04-18 15:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca6f69f0ebf1252262b61d765543fc818a6c1f67">ca6f69f0ebf1252262b61d765543fc818a6c1f67</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/manuelecastro/liferay-portal/tree/LPS-181652">LPS-181652</a><br/>Branch GIT ID: <a href="https://github.com/manuelecastro/liferay-portal/commit/51203f7eece4f5b5851757be4f98b5ebd1f3f372">51203f7eece4f5b5851757be4f98b5ebd1f3f372</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5113/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5113/jenkins-report.html">here</a>.</h5></details></html>

2023-04-18 17:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/10715/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10715/jenkins-report.html">here</a>.</b></p>

2023-04-18 18:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed</h3><h3>:x: ci:test:relevant - 64 out of 67 jobs passed in 1 hour 44 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4469">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_10715</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca6f69f0ebf1252262b61d765543fc818a6c1f67">ca6f69f0ebf1252262b61d765543fc818a6c1f67</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5490c9024dbabbc8d77782664dfb72584374910">b5490c9024dbabbc8d77782664dfb72584374910</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2273322360">EE Development Acceptance (master) - 4468 - 2023-04-18[04:38:19]</a></p><details><summary><strong>ci:test:stable - 28 out of 28 jobs PASSED</strong></summary><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 64 out of 67 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/10715/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/528413/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485752/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580038/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477627/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/555883/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485750/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/555884/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/493843/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/528412/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452610/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/80555/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580036/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346207/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477631/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/528418/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/528419/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183801/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/528417/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477629/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/538502/">functional-tomcat90-mysql57-chrome100-jdk8/0/7</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477630/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/8</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495541/">functional-tomcat90-mysql57-chrome100-jdk8/0/9</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452614/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477628/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333636/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495539/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/446783/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/80558/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/180915/">functional-upgrade-tomcat90-mysql57-jdk8/0/6</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/493842/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/528416/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495537/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485751/">js-unit-jdk8/0/0</a></li>< [...]

2023-04-18 18:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/10715/">test-portal-acceptance-pullrequest(master)#10715</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10715/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/4229">liferay-lima#4229</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2273449911">[master] ci:test:relevant - manuelecastro &gt; liferay-lima - PR#4229 - 2023-04-18[10:07:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/23781/">publish-testray-report#23781</a><br/></div></div>

2023-04-18 21:10 UTC, manuelecastro commented
ci:reevaluate:1377401_10715

2023-04-18 21:10 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1377401_10715` against the latest valid upstream results.

2023-04-18 21:14 UTC, liferay-continuous-integration commented
<p>Unable to <a href="https://test-1-21.liferay.com/job/test-portal-evaluate-pullrequest/60/">reevaluate</a> previous pull request result. Please wait for this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4470">acceptance upstream build</a> to complete, and attempt reevaluation again with the CI command:
<pre>ci:reevaluate:1377401_10715</pre></p>

2023-04-19 07:26 UTC, AliciaGarciaGarcia commented
Hi @manuelecastro 

We think that this not an issue, this should be the expected behavior.
The parent article works as a container; if you cannot see the container (parent), you shouldn't see the content (child articles).

If you have questions with this, you can reach us on the #t-dxp-lima slack channel.

Thanks for all

2023-04-19 19:37 UTC, manuelecastro commented
Hi @AliciaGarciaGarcia !

I believe I expressed myself wrong, sorry about that. I meant that it IS possible to see the parent's content but it's **not** possible to see the **child's** content page. 

Here is a video of the bug being reproduced. What do you think?

Thanks! :)

https://user-images.githubusercontent.com/72988896/233180952-fc0177d2-3199-422b-95e8-73a9b76a584d.mp4

2023-04-21 08:34 UTC, AliciaGarciaGarcia requested changes

2023-04-26 22:42 UTC, manuelecastro commented on modules/apps/knowledge-base/knowledge-base-service/src/main/java/com/liferay/knowledge/base/model/impl/KBArticleImpl.java
> +			parentResourcePrimKey, WorkflowConstants.STATUS_ANY);
@liferay-lima Hi! 

I'm a little bit lost on what kind of approach I could take here. What did Alicia meant when she said the problem is more on the "vertical panel"? Do you know the files that I could look for to make this fix?

Thanks!

2023-04-27 06:24 UTC, adolfopa commented on modules/apps/knowledge-base/knowledge-base-service/src/main/java/com/liferay/knowledge/base/model/impl/KBArticleImpl.java
> +			parentResourcePrimKey, WorkflowConstants.STATUS_ANY);
Hey @manuelecastro 
Sorry for the lack of response, but we have some urgent (and unplanned) tasks in our hands right now. Would it be possible to put this on hold for a while until we have more time to look into this?
Thanks!

2023-05-03 14:18 UTC, adolfopa requested changes

2023-05-03 14:18 UTC, adolfopa commented on modules/apps/knowledge-base/knowledge-base-service/src/main/java/com/liferay/knowledge/base/model/impl/KBArticleImpl.java
> +			parentResourcePrimKey, WorkflowConstants.STATUS_ANY);
@manuelecastro As @AliciaGarciaGarcia said, this fix should be done only for the side panel (there are other usages of that method that expect approved items).

The simplest fix that should work is simply to inline the `getParentKBArticle` code in the `_getParentNode` method. Something like:
```
    private String _getParentNodeURL(KBArticle kbArticle)
		throws PortalException {

		long parentResourcePrimKey = kbArticle.getParentResourcePrimKey();

		if ((parentResourcePrimKey <= 0) ||
			(kbArticle.getParentResourceClassNameId() !=
			 	kbArticle.getClassNameId())) {

			return _createKBFolderRenderURL(kbArticle.getKbFolderId());
		}

		KBArticle parentKBArticle =
			KBArticleLocalServiceUtil.getLatestKBArticle(
				parentResourcePrimKey, WorkflowConstants.STATUS_ANY);

		return _createKBArticleRenderURL(parentKBArticle);
	} 
```

2023-05-03 20:51 UTC, diogomelo09 commented
ci:close

2023-05-03 20:51 UTC, closed without merging

2023-05-03 20:55 UTC, diogomelo09 commented
Hi @liferay-lima ! 
Since @manuelecastro is on another team, I'm now handling this ticket for her. 
I resent the PR with the asked modifications here: https://github.com/liferay-lima/liferay-portal/pull/4273