LPS-195201 Use setURLBackTitle parameter to indicate the title in the knowledge-base-web module
liferay-lima/liferay-portal pull request #4661
Opened 2023-09-05 13:29 UTC by Stephy6

2023-09-05 13:29 UTC, liferay-lima commented
ci:test:sf

2023-09-05 13:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-05 13:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5358/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5358/jenkins-report.html">here</a>.</b></p>

2023-09-05 13:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2cb8c96b7d04b470df84b038d2e51df439681460">2cb8c96b7d04b470df84b038d2e51df439681460</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Stephy6/liferay-portal/tree/LPS-195201">LPS-195201</a><br/>Branch GIT ID: <a href="https://github.com/Stephy6/liferay-portal/commit/7e1c242ae321584f2408e68b2a2f30ed296dea4b">7e1c242ae321584f2408e68b2a2f30ed296dea4b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5358/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5358/jenkins-report.html">here</a>.</h5></details></html>

2023-09-05 13:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5358/">test-portal-source-format#5358</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5358/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/4661">liferay-lima#4661</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2418851414">[master] ci:test:sf - Stephy6 &gt; liferay-lima - PR#4661 - 2023-09-05[06:29:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/4030/">publish-testray-report#4030</a><br/></div></div>

2023-09-06 06:10 UTC, adolfopa requested changes

2023-09-06 06:10 UTC, adolfopa commented on modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/edit_kb_article.jsp
> +	portletDisplay.setURLBackTitle(kbArticle.getTitle());
You need to keep the three calls to `portletDisplay` methods as a block, and separate them from the `renderResponse` one. Something like:
```
portletDisplay.set...();
portletDisplay.set...();
portletDisplay.set...();l

renderResponse.set...();
```
Make sure this calls are alphabetically sorted.

2023-09-06 06:10 UTC, adolfopa commented on modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/edit_kb_article.jsp
> +KBArticle kbArticle = editKBArticleDisplayContext.getKBArticle();
The `getKBArticle` method caches the value. Can you inline all calls to `editKBArticleDisplayContext.getKBArticle()`?

2023-09-07 05:27 UTC, adolfopa requested changes

2023-09-07 05:27 UTC, adolfopa commented on modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/edit_kb_article.jsp
> +			"kbArticle", kbArticle
Can you inline this?

2023-09-07 07:19 UTC, Stephy6 commented on modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/edit_kb_article.jsp
> +			"kbArticle", kbArticle
Sure, thank you!

2023-09-07 14:53 UTC, adolfopa approved these changes

2023-09-07 14:54 UTC, adolfopa commented
ci:forward

2023-09-07 14:54 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-09-07 14:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5647/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5647/jenkins-report.html">here</a>.</b></p>

2023-09-07 14:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bb2e86dc48c9154cb076f1a44e166c21c8f26df0">bb2e86dc48c9154cb076f1a44e166c21c8f26df0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Stephy6/liferay-portal/tree/LPS-195201">LPS-195201</a><br/>Branch GIT ID: <a href="https://github.com/Stephy6/liferay-portal/commit/41673138fdbc8061b2043e39ce3f8f98fc35fb06">41673138fdbc8061b2043e39ce3f8f98fc35fb06</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5647/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5647/jenkins-report.html">here</a>.</h5></details></html>

2023-09-07 15:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/9934/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9934/jenkins-report.html">here</a>.</b></p>

2023-09-07 18:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 30 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 62 out of 72 jobs passed in 2 hours 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bb2e86dc48c9154cb076f1a44e166c21c8f26df0">bb2e86dc48c9154cb076f1a44e166c21c8f26df0</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a9e2c728a149462eba7c34aa31b4ac417bccc57d">a9e2c728a149462eba7c34aa31b4ac417bccc57d</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2420246145">EE Development Acceptance (master) - 5 - 2023-09-07[00:39:54]</a></p><details><summary><strong>ci:test:stable - 30 out of 30 jobs PASSED</strong></summary><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 62 out of 72 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/9934/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/805250/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/722633/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/582824/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/805268/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/722625/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280092/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246422/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246426/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/805249/"><strike>functional-smoke-tomcat90-postgresql144-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/805275/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830701/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707836/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313543/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569264/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262006/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674678/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/2</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/659522/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/3</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263060/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/4</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263444/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/5</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674677/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/264124/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/7</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258658/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/8</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/282975/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/9</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263053/">functional-tomcat90-mysql57-chrome100-jdk8/0/10</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291343/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/722628/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263059/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/730153/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229537/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/640552/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291342/">functional-upgrade-tomcat90-mysql57-jdk8/0/6</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628040/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/730146/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830714/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-do [...]

2023-09-07 18:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/9934/">test-portal-acceptance-pullrequest(master)#9934</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9934/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-lima/liferay-portal/pull/4661">liferay-lima#4661</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2420431458">[master] ci:test:relevant - Stephy6 &gt; liferay-lima - PR#4661 - 2023-09-07[08:31:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/21604/">publish-testray-report#21604</a><br/></div></div>

2023-09-08 04:26 UTC, Jeremy-Ch commented
Hi @Stephy6 The below error is related to this pr. Please help to take a look. Thanks.

How to reproduce:

1. Go to KB admin
2. Click "+"> Click "Basic Article"

The error "Knowledge Base is temporarily unavailable" is displayed.
![image](https://github.com/liferay-lima/liferay-portal/assets/48118285/62fa7baa-d47c-4b78-a8c6-9c59137518c7)

**Console error:**
```
beanshell] 2023-09-07 17:39:40.811 ERROR [http-nio-8080-exec-5][PortletRequestDispatcherImpl:295] Unable to dispatch request: java.lang.NullPointerException
[beanshell] 2023-09-07 17:39:40.812 ERROR [http-nio-8080-exec-5][PortletServlet:109] Unable to process portlet com_liferay_knowledge_base_web_portlet_AdminPortlet: org.apache.jasper.JasperException: java.lang.NullPointerException
[beanshell] javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
[beanshell] 	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:298) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:114) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:611) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:627) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:497) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.knowledge.base.web.internal.portlet.AdminPortlet.doDispatch(AdminPortlet.java:147) ~[bundleFile:?]
[beanshell] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:300) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.knowledge.base.web.internal.portlet.BaseKBPortlet.render(BaseKBPortlet.java:75) ~[bundleFile:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:118) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:49) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:115) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:62) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:105) ~[portal-kernel.jar:?]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:566) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:656) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:342) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.lambda$render$0(MonitoringInvokerPortlet.java:250) ~[?:?]
[beanshell] 	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet._render(MonitoringInvokerPortlet.java:353) ~[?:?]
[beanshell] 	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.render(MonitoringInvokerPortlet.java:248) ~[?:?]
[beanshell] 	at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1407) ~[?:?]
[beanshell] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.75]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
[beanshell] 	at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:55) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:181) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:70) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:44) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.servlet.TransferHeadersHelperUtil$TransferHeadersRequestDispatcher.include(TransferHeadersHelperUtil.java:152) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl._render(PortletContainerImpl.java:890) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl.lambda$render$2(PortletContainerImpl.java:214) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:412) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl.render(PortletContainerImpl.java:202) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.SecurityPortletContainerWrapper.render(SecurityPortletContainerWrapper.java:125) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.RestrictPortletContainerWrapper.lambda$render$0(RestrictPortletContainerWrapper.java:115) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.RestrictPortletContainerWrapper._render(RestrictPortletContainerWrapper.java:176) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.RestrictPortletContainerWrapper.render(RestrictPortletContainerWrapper.java:113) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.PortletContainerUtil.render(PortletContainerUtil.java:205) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.processMax(TemplateProcessor.java:134) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor3980.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505) ~[bundleFile:?]
[beanshell] 	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72) ~[bundleFile:?]
[beanshell] 	at freemarker.core.MethodCall._eval(MethodCall.java:62) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Expression.eval(Expression.java:101) ~[bundleFile:?]
[beanshell] 	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) ~[bundleFile:?]
[beanshell] 	at freemarker.core.DollarVariable.accept(DollarVariable.java:63) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Environment.visit(Environment.java:331) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Environment.visit(Environment.java:337) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Environment.process(Environment.java:310) ~[bundleFile:?]
[beanshell] 	at freemarker.template.Template.process(Template.java:383) ~[bundleFile:?]
[beanshell] 	at com.liferay.portal.template.freemarker.internal.FreeMarkerTemplate.lambda$processTemplate$0(FreeMarkerTemplate.java:148) ~[bundleFile:?]
[beanshell] 	at com.liferay.portal.template.freemarker.internal.FreeMarkerManager.render(FreeMarke [...]

2023-09-08 07:57 UTC, Stephy6 commented
For the moment I have to close this PR because of some changes we're making related to setBackURLTitles, sorry for the time.

2023-09-08 07:57 UTC, closed without merging